### ISSUE TITLE
Linux build: GTK issues

### ISSUE THREAD

**Issue by apple314159** [SSARCandy/Coherent-Line-Drawing#11]
I did a build on Linux. When I ran the generated executable I got the error:

``
$ ./Coherent-Line-Drawing 
(Coherent-Line-Drawing:1385): Gtk-ERROR **: 17:42:02.514: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap (core dumped)
``

Before I dig deeper into this problem, has anyone else built a Linux version?

**Comment by Balupurohit23** [comment]
> I did a build on Linux. When I ran the generated executable I got the error:
> 
> `$ ./Coherent-Line-Drawing (Coherent-Line-Drawing:1385): Gtk-ERROR **: 17:42:02.514: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported Trace/breakpoint trap (core dumped)`
> 
> Before I dig deeper into this problem, has anyone else built a Linux version?

No, even I am having issues in the building.
Have you built it?

**Comment by SSARCandy** [comment]
which platform you use?

**Comment by SSARCandy** [comment]
I have just tried it on ubuntu, here is the step by step instructions:

```sh
# install opencv pkg
$ sudo apt-get install libopencv-dev libcv-dev

# install wxwidget pkg
$ sudo apt install libwxgtk3.0-0v5-dbg libwxgtk3.0-dev

# build project
$ mkdir build
$ cd build
$ cmake ..
$ make
```

I didn't face any issue to run the program, can you provide your environment?

**Comment by Balupurohit23** [comment]
> I have just tried it on ubuntu, here is the step by step instructions:
> 
> ```shell
> # install opencv pkg
> $ sudo apt-get install libopencv-dev libcv-dev
> 
> # install wxwidget pkg
> $ sudo apt install libwxgtk3.0-0v5-dbg libwxgtk3.0-dev
> 
> # build project
> $ mkdir build
> $ cd build
> $ cmake ..
> $ make
> ```
> 
> I didn't face any issue to run the program, can you provide your environment?

Hi, I am using **ubuntu 16.04 LTS 64-bit**. I tried your steps but I got the following error about the scope during the last step.
```
Scanning dependencies of target Coherent-Line-Drawing
[ 16%] Building CXX object CMakeFiles/Coherent-Line-Drawing.dir/src/main.cpp.o
[ 33%] Building CXX object CMakeFiles/Coherent-Line-Drawing.dir/src/ETF.cpp.o
[ 50%] Building CXX object CMakeFiles/Coherent-Line-Drawing.dir/src/CLD.cpp.o
[ 66%] Building CXX object CMakeFiles/Coherent-Line-Drawing.dir/src/postProcessing.cpp.o
/home/m1047237/Jupyter/Torch/segmentation/Coherent-Line-Drawing-master/src/postProcessing.cpp: In member function ‘void PP::FlowField(cv::Mat&, cv::Mat&)’:
/home/m1047237/Jupyter/Torch/segmentation/Coherent-Line-Drawing-master/src/postProcessing.cpp:66:61: error: ‘arrowedLine’ was not declared in this scope
    arrowedLine(dis, p, p2, Scalar(255,0,  0), 1.5, 8, 0, 0.3);
                                                             ^
CMakeFiles/Coherent-Line-Drawing.dir/build.make:134: recipe for target 'CMakeFiles/Coherent-Line-Drawing.dir/src/postProcessing.cpp.o' failed
make[2]: *** [CMakeFiles/Coherent-Line-Drawing.dir/src/postProcessing.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Coherent-Line-Drawing.dir/all' failed
make[1]: *** [CMakeFiles/Coherent-Line-Drawing.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SSARCandy** [comment]
think your opencv is not higher than 3.0, you can comment out that line if you cannot install opencv > 3.0

**Comment by Balupurohit23** [comment]
> think your opencv is not higher than 3.0, you can comment out that line if you cannot install opencv > 3.0

My OpenCV version is '3.4.4'.

**Comment by SSARCandy** [comment]
then it should not have the error, can you check is the opencv version you linked is correct?
