### ISSUE TITLE
how to use release-windows correctly? it does work sometimes

### ISSUE THREAD

**Issue by nywang2019** [SSARCandy/Coherent-Line-Drawing#27]
i downloaded the Coherent Line Drawing-release-windows,  however, it does not work sometimes with some images, i do not know why?  the result, even the original image will be a whole black one after my operation.  any one can tell me how to use this GUI correctly?  maybe my operation is wrong. Thanks in advance.

**Comment by SSARCandy** [comment]
can you list out a step by step to create a whole black result? 
so that I can use this information to identify the issue.
It may be a bug. 😅

**Comment by nywang2019** [comment]
thanks for the reply.  It's ok now since I select each step from the dropdown menu one by one without skipping over any of them.  but I still have some questions:
1: when to use "smooth ETF" ? in "ETF debug" or "ETF" step?
2: what is the parameter "noise" for?
3: is it possible to generate a single line drawing? if so, how?

**Comment by SSARCandy** [comment]
1. there is no different when you smooth ETF at ETF or ETF-debug
2. the parameters description is clear in the original paper, read it would help.
3. there is a command line application can use if you build from source code, it will directly generate a single line drawing image.

**Comment by nywang2019** [comment]
ok, thanks a lot!

**Comment by SSARCandy** [comment]
@nywang2019 if could I still want to know how to produce a whole black result.
Since it should not need to change to correspond mode to perform actions by design.
Thanks if you can tell me. 😄
