### ISSUE TITLE
Boost was missing in the requirement

### ISSUE THREAD

**Issue by Dcruise546** [SSARCandy/Coherent-Line-Drawing#31]
Technically, this does not count as an issue. 
But, the Wiki section mentions only OpenCV and WxWidgets as external library dependencies and not the Boost library.

While compiling even with the Boost linked to my IDE, I get the following error.

> undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'

This is same for each line of code which has a link to the boost library. I am using Windows 10 with Code::Blocks

**Comment by SSARCandy** [comment]
boost is not required if you only want to build GUI, you can comment it out in CMakelist.txt

for the boost library, you need to link boost_program_option.

also thank you to point it out, I'll make it more clear in readme

**Comment by Dcruise546** [comment]
I did not use the Cmake to build the project. I used the IDE and directly linked my libraries to build them. 

However, when I use the Cmake to build, I get the error message saying:

> CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindwxWidgets.cmake:1008 (find_package_handle_standard_args)
  CMakeLists.txt:15 (FIND_PACKAGE)

Meanwhile, I inserted the following lines in my CMakelist.txt to link my libraries:
`set("OpenCV_DIR" "C:/opencv/build/install")
set("wxWidgets_INCLUDE_DIRS" "C:/wxWidgets_include/include")
set("wxWidgets_LIBRARIES" "C:/wxWidgets_include/lib/gcc920TDM_x64_dll")`

OpenCV did not throw such an error and only WxWidgets does it.

**Comment by SSARCandy** [comment]
I guess `wxWidgets_LIBRARIES` is setting wrong, usually, you only need to set `wxWidgets_ROOT_DIR`, and CMake will find what it need itself.
here is a screenshot of CMake GUI I use to build this project under Windows 10, hope it would help
![image](https://user-images.githubusercontent.com/6803791/96578565-fc170d00-1307-11eb-8d56-0a3f70a852a4.png)

**Comment by Dcruise546** [comment]
For some reason, this method seems to work without an issue. 
Thanks so much for the help. Was searching for OpenCV and WxWidgets project to start with. This project was reallly helpful.

With this, I will close this issue.
