### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by computer-science-student** [SSARCandy/Coherent-Line-Drawing#36]
Hi,
I am having trouble installing Coherent-Line-Drawing on Linux.

I downloaded this: https://github.com/SSARCandy/Coherent-Line-Drawing/archive/refs/tags/v1.0.3.zip but when I tried to run ./build.sh  from that directory, I got the following error message:

~/Coherent-Line-Drawing-1.0.3$ ./build.sh 
/usr/bin/nproc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/build
[  9%] Building CXX object CMakeFiles/Coherent-Line-Drawing.dir/src/ETF.cpp.o
[ 18%] Building CXX object CMakeFiles/cld.dir/src/cmd.cpp.o
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/ETF.cpp: In member function ‘void ETF::initial_ETF(std::string, cv::Size)’:
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/ETF.cpp:33:47: error: ‘CV_INTER_LINEAR’ was not declared in this scope
   33 |     cv::resize(flowField, flowField, s, 0, 0, CV_INTER_LINEAR);
      |                                               ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/Coherent-Line-Drawing.dir/build.make:90: CMakeFiles/Coherent-Line-Drawing.dir/src/ETF.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/Coherent-Line-Drawing.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 27%] Building CXX object CMakeFiles/cld.dir/src/ETF.cpp.o
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/cmd.cpp: In function ‘int main(int, char**)’:
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/cmd.cpp:87:42: error: ‘CV_GRAY2RGB’ was not declared in this scope
   87 |     cv::cvtColor(cld.result, cld.result, CV_GRAY2RGB);
      |                                          ^~~~~~~~~~~
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/cmd.cpp:95:40: error: ‘CV_GRAY2BGR’ was not declared in this scope
   95 |         cv::cvtColor(vis_etf, vis_etf, CV_GRAY2BGR);
      |                                        ^~~~~~~~~~~
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/cmd.cpp:101:42: error: ‘CV_RGB2BGR’ was not declared in this scope; did you mean ‘CV_RGB’?
  101 |         cv::cvtColor(vis_flow, vis_flow, CV_RGB2BGR);
      |                                          ^~~~~~~~~~
      |                                          CV_RGB
make[2]: *** [CMakeFiles/cld.dir/build.make:76: CMakeFiles/cld.dir/src/cmd.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/ETF.cpp: In member function ‘void ETF::initial_ETF(std::string, cv::Size)’:
/home/jl/Documents/University/2024/Spring_2024/Paper/program/cpp11/Coherent-Line-Drawing-1.0.3/src/ETF.cpp:33:47: error: ‘CV_INTER_LINEAR’ was not declared in this scope
   33 |     cv::resize(flowField, flowField, s, 0, 0, CV_INTER_LINEAR);
      |                                               ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/cld.dir/build.make:90: CMakeFiles/cld.dir/src/ETF.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/cld.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

How do you get around these error messages to install Coherent-Line-Drawing on Linux?

Thanks!

**Comment by SSARCandy** [comment]
please make sure you're opencv version is 3

**Comment by computer-science-student** [comment]
Hi, thank you for getting back to me so fast!

The code failed to compile because I was using opencv version 4.

I have been trying to compile opencv version 3 from source on Debian 12 stable. I installed all of the dependencies needed for compiling opencv-3.4.16, the latest version of version 3, but I wasn't able to compile version 3.4.16 on Debian 12. Opencv version 3.4.16 is too outdated for my operating system, Debian 12. I am not sure how to get OpenCV version 3.

Which Linux distribution do you recommend for this version of OpenCV?

Ubuntu or Debian and which version? Ubuntu 20/22 or Debian 10/11?

Thank you!

**Comment by SSARCandy** [comment]
using docker to get older version of Ubuntu would be easier, you can check my CI scripts, https://github.com/SSARCandy/Coherent-Line-Drawing/blob/master/.github/workflows/c-cpp.yml
it is using Ubuntu 18.04

**Comment by computer-science-student** [comment]
Thank you for getting back to me and for opening up the issue for upgrading to opencv 4. Your support really helps.

**Comment by SSARCandy** [comment]
i'll close this issue since it is expected compile requirement as the moment (until I get time to upgrade to opencv 4)
