### ISSUE TITLE
undeclared fn arrowedLine in src/postProcessing.cpp

### ISSUE THREAD

**Issue by eritain** [SSARCandy/Coherent-Line-Drawing#9]
I'm running gcc 4.8.4 on Ubuntu 14.04.3 "Trusty Tahr" and have installed cmake, libwxgtk3.0-dev, and libopencv-dev. 

Compiling fails:

`/home/eritain/Coherent-Line-Drawing/src/postProcessing.cpp: In member function ‘void PP::FlowField(cv::Mat&, cv::Mat&)’:
/home/eritain/Coherent-Line-Drawing/src/postProcessing.cpp:66:61: error: ‘arrowedLine’ was not declared in this scope
    arrowedLine(dis, p, p2, Scalar(255,0,  0), 1.5, 8, 0, 0.3);
                                                             ^`

In OpenCV 3.0, arrowedLine is declared in opencv2/imgproc/imgproc.hpp but I lack the know-how to include that in either include/postProcessing.h or src/postProcessing.cpp (I tried, but no luck). What do?

EDIT: I installed 3.0 but it's still looking at 2.4.8?!

**Comment by SSARCandy** [comment]
`arrowedLine` is not present in OpenCV <= 2.4.9
(ref: https://stackoverflow.com/questions/33841559/opencv-arrowedline-function)

I think this is your OpenCV version's problem, can you try to uninstall the old version of OpenCV?

**Comment by eritain** [comment]
Yes, uninstalling OpenCV and recompiling the new version fixed the problem.
